CoralliumServerBundle\Entity\Profile:
    type: entity
    table: null
    repositoryClass: CoralliumServerBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        identity:
            type: string
            length: 255
        birthday:
            type: date

    oneToOne:
        address:
          targetEntity: CoralliumServerBundle\Entity\Address

    lifecycleCallbacks: {  }
