CoralliumServerBundle\Entity\Project:
    type: entity
    table: null
    repositoryClass: CoralliumServerBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text

    oneToMany:
        subprojects:
            targetEntity: CoralliumServerBundle\Entity\SubProject
            mappedBy: project
    lifecycleCallbacks: {  }
