<?php

namespace CoralliumServerBundle\Repository;

/**
 * OutcomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutcomeRepository extends \Doctrine\ORM\EntityRepository
{
}
