<?php

namespace CoralliumServerBundle\Repository;

/**
 * RetributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetributionRepository extends \Doctrine\ORM\EntityRepository
{
}
