<?php

namespace CoralliumServerBundle\Repository;

/**
 * SubprojectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubprojectRepository extends \Doctrine\ORM\EntityRepository
{
}
